language: node_js
node_js:
  - 'stable'

script:
  - npm install
  - npm test
  - npm build

deploy:
  provider: surge
  skip_cleanup: ture
  domain: project-stopwatch.surge.sh
  project: ./build/

on:
  branch: master